import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'fs';
import path from 'path';
import {
  COMPANIES, ADJACENT, LINKS_PER_PAGE, START, END, relatedFor, block, extractBlock,
} from '../scripts/build-company-crosslinks.mjs';

// The "Other companies that ask similar SQL" strip on every
// /{company}-sql-interview/ page is GENERATED by
// scripts/build-company-crosslinks.mjs. On 2026-09-07 the two fell out of
// sync: /capital-one-sql-interview/ shipped and a sixth card was hand-added to
// seven fintech strips, while the script still emitted five — so the next
// `node scripts/build-company-crosslinks.mjs` would have silently dropped
// Capital One from most of them and re-orphaned the newest page. Nothing
// caught it, because nothing bound the pages to the generator.
//
// This file is that binding. Every committed strip must be byte-identical to
// what the script produces today. If you hand-edit a strip, this fails; edit
// the script and re-run it instead.

const ROOT = path.join(import.meta.dirname, '..');
const SRC = path.join(ROOT, 'src');

let pages;   // { slug, file, html }

beforeAll(() => {
  pages = Object.keys(COMPANIES).map(slug => {
    const file = path.join(SRC, `${slug}-sql-interview.html`);
    return { slug, file, html: fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null };
  });
});

describe('company cross-link strips are the generator\'s output', () => {
  it('every company in the registry has a page, and every page a registry entry', () => {
    const missing = pages.filter(p => p.html === null).map(p => p.slug);
    expect(missing, `registry names a page that does not exist: ${missing.join(', ')}`).toEqual([]);

    const onDisk = fs.readdirSync(SRC)
      .filter(f => /-sql-interview\.html$/.test(f))
      .map(f => f.slice(0, -'-sql-interview.html'.length))
      .sort();
    expect(onDisk, 'a company page exists that the generator does not know about — it would be skipped and orphaned')
      .toEqual(Object.keys(COMPANIES).sort());
  });

  it('each page carries exactly one strip, byte-identical to the generator', () => {
    const offenders = [];
    for (const { slug, html } of pages) {
      if (html === null) continue;
      const starts = (html.match(new RegExp(START, 'g')) || []).length;
      if (starts !== 1) { offenders.push(`${slug}: ${starts} strips (expected 1)`); continue; }
      const committed = extractBlock(html);
      if (committed !== block(slug)) {
        offenders.push(`${slug}: strip differs from the generator — re-run node scripts/build-company-crosslinks.mjs`);
      }
    }
    expect(offenders, offenders.join('\n')).toEqual([]);
  });

  it('every strip links LINKS_PER_PAGE real sibling pages, never itself', () => {
    for (const { slug, html } of pages) {
      if (html === null) continue;
      const strip = extractBlock(html);
      const hrefs = [...strip.matchAll(/href="\/([a-z0-9-]+)-sql-interview\/"/g)].map(m => m[1]);
      expect(hrefs.length, `${slug} strip link count`).toBe(LINKS_PER_PAGE);
      expect(new Set(hrefs).size, `${slug} strip has a duplicate link`).toBe(hrefs.length);
      expect(hrefs, `${slug} links to itself`).not.toContain(slug);
      for (const h of hrefs) expect(COMPANIES[h], `${slug} links to unknown ${h}`).toBeTruthy();
    }
  });

  it('no page is orphaned — every company receives inbound links', () => {
    const inbound = {};
    for (const slug of Object.keys(COMPANIES)) {
      for (const k of relatedFor(slug)) inbound[k] = (inbound[k] || 0) + 1;
    }
    const orphans = Object.keys(COMPANIES).filter(k => !inbound[k]);
    expect(orphans, `zero inbound links: ${orphans.join(', ')} — the exact defect the generator exists to fix`).toEqual([]);
    // Capital One is the newest page and the one the drift would have dropped.
    expect(inbound['capital-one'], 'capital-one inbound links').toBeGreaterThanOrEqual(3);
  });

  it('the registry is internally consistent — every sector has an adjacency list', () => {
    const sectors = [...new Set(Object.values(COMPANIES).map(c => c.sector))];
    for (const s of sectors) {
      expect(ADJACENT[s], `sector "${s}" has no adjacency list; relatedFor would throw`).toBeTruthy();
      for (const adj of ADJACENT[s]) {
        expect(sectors, `sector "${s}" is adjacent to "${adj}", which no company belongs to`).toContain(adj);
      }
    }
    for (const [slug, c] of Object.entries(COMPANIES)) {
      expect(c.name, `${slug} has no name`).toBeTruthy();
      expect(c.desc, `${slug} has no descriptor`).toBeTruthy();
      expect(c.desc.length, `${slug} descriptor is too long for the card`).toBeLessThan(80);
    }
  });

  it('the strip stays inside the design system — no accent yellow in navigation', () => {
    // DESIGN.md: #FFE34D is for primary CTAs, XP, streaks and win states only.
    for (const { slug, html } of pages) {
      if (html === null) continue;
      expect(extractBlock(html).toUpperCase(), `${slug} strip uses the accent colour`).not.toContain('FFE34D');
    }
  });
});
