// The neobank ledger (src/data/neobank-data.js, key finans_neobank) is
// generated by scripts/generate-neobank-ledger.js with a fixed seed. These
// tests pin the invariants a running-balance or cohort query relies on, and
// the two facts that would otherwise drift silently: that the file is in the
// data bundle, and that it stays small enough to be inlined.
import { describe, it, expect } from 'vitest';
import { readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import Database from 'better-sqlite3';
import { dataFiles } from '../scripts/data-files.js';

const here = (rel) => fileURLToPath(new URL(rel, import.meta.url));
const DATA = here('../src/data/neobank-data.js');

function loadDataset() {
  const sb = { window: {}, console: { log() {} } };
  vm.createContext(sb);
  vm.runInContext(readFileSync(DATA, 'utf8'), sb);
  return sb.window.publicDatasetsData.finans_neobank;
}

function openDb(ds) {
  const db = new Database(':memory:');
  for (const [name, t] of Object.entries(ds.tables)) {
    const types = t.columns.map((_, i) => { const s = t.data.find(r => r[i] !== null)?.[i]; return typeof s === 'number' ? (Number.isInteger(s) ? 'INTEGER' : 'REAL') : 'TEXT'; });
    db.exec(`CREATE TABLE ${name} (${t.columns.map((c, i) => `${c} ${types[i]}`).join(', ')})`);
    const ins = db.prepare(`INSERT INTO ${name} VALUES (${t.columns.map(() => '?').join(',')})`);
    db.transaction(rows => rows.forEach(r => ins.run(r)))(t.data);
  }
  return db;
}

const COMPLETED_DELTAS = `SELECT user_id, ts, amount_gbp AS delta, 0 AS k FROM top_ups
  UNION ALL SELECT user_id, ts, CASE WHEN type='transfer_in' THEN amount_gbp ELSE -(amount_gbp + fee_gbp) END,
                   CASE WHEN type='transfer_in' THEN 1 ELSE 2 END FROM transactions WHERE status='completed'`;

describe('neobank ledger — shape and shipping', () => {
  const ds = loadDataset();

  it('has the four tables the archetype needs, with the columns the questions name', () => {
    expect(Object.keys(ds.tables).sort()).toEqual(['currencies', 'top_ups', 'transactions', 'users']);
    expect(ds.tables.users.columns).toEqual(['user_id', 'signup_date', 'country', 'home_currency', 'plan', 'plan_since', 'kyc_verified_at', 'referred_by', 'birth_year']);
    expect(ds.tables.transactions.columns).toContain('amount_gbp');
    expect(ds.tables.transactions.columns).toContain('counterparty_user_id');
    expect(ds.tables.top_ups.columns).toContain('method');
    expect(ds.tables.currencies.columns).toEqual(['code', 'name', 'rate_to_gbp']);
  });

  it('is in the data bundle, after the fraud ledger and before the sector challenges', () => {
    const i = dataFiles.indexOf('neobank-data.js');
    expect(i).toBeGreaterThan(dataFiles.indexOf('finans-fraud-data.js'));
    expect(i).toBeLessThan(dataFiles.indexOf('sector-challenges.js'));
  });

  it('stays small enough to inline (< 450 KB) and is a generated file with a fixed seed', () => {
    expect(statSync(DATA).size).toBeLessThan(450 * 1024);
    const head = readFileSync(DATA, 'utf8').slice(0, 600);
    expect(head).toMatch(/DO NOT EDIT BY HAND/);
    expect(head).toMatch(/seed 20260912/);
  });

  it('is sized like a screen dataset, not a toy and not a warehouse', () => {
    expect(ds.tables.users.data.length).toBe(240);
    expect(ds.tables.transactions.data.length).toBeGreaterThan(1500);
    expect(ds.tables.transactions.data.length).toBeLessThan(4000);
    expect(ds.tables.top_ups.data.length).toBeGreaterThan(400);
  });
});

describe('neobank ledger — money reconciles', () => {
  const db = openDb(loadDataset());
  const one = (sql) => db.prepare(sql).get();

  it('every money row belongs to a KYC-verified user and postdates their KYC', () => {
    expect(one(`SELECT count(*) AS n FROM (SELECT user_id, ts FROM top_ups UNION ALL SELECT user_id, ts FROM transactions) x
                LEFT JOIN users u USING(user_id) WHERE u.user_id IS NULL OR u.kyc_verified_at IS NULL OR x.ts < u.kyc_verified_at`).n).toBe(0);
  });

  it('amount_gbp is the amount times the currency rate, on every row', () => {
    expect(one(`SELECT count(*) AS n FROM (SELECT amount, currency, amount_gbp FROM transactions UNION ALL SELECT amount, currency, amount_gbp FROM top_ups) x
                JOIN currencies c ON c.code = x.currency WHERE abs(round(x.amount * c.rate_to_gbp, 2) - x.amount_gbp) > 0.011`).n).toBe(0);
  });

  it('the running balance never goes negative on completed rows, for any user', () => {
    const r = one(`WITH ev AS (${COMPLETED_DELTAS}), run AS (SELECT SUM(delta) OVER (PARTITION BY user_id ORDER BY ts, k ROWS UNBOUNDED PRECEDING) AS bal FROM ev)
                   SELECT count(*) AS n, min(bal) AS lowest FROM run`);
    expect(r.n).toBeGreaterThan(0);
    expect(r.lowest).toBeGreaterThanOrEqual(-0.011);
  });

  it('every insufficient_funds decline was genuinely short at that moment', () => {
    expect(one(`SELECT count(*) AS n FROM transactions d WHERE d.decline_reason = 'insufficient_funds' AND
                  (SELECT COALESCE(SUM(delta), 0) FROM (${COMPLETED_DELTAS}) e WHERE e.user_id = d.user_id AND e.ts <= d.ts) >= d.amount_gbp + d.fee_gbp`).n).toBe(0);
  });

  it('p2p transfers are written as matched pairs', () => {
    expect(one(`SELECT count(*) AS n FROM transactions o LEFT JOIN transactions i ON i.type='transfer_in' AND i.user_id = o.counterparty_user_id
                AND i.counterparty_user_id = o.user_id AND i.ts = o.ts AND i.amount_gbp = o.amount_gbp
                WHERE o.type='transfer_out' AND o.status='completed' AND i.txn_id IS NULL`).n).toBe(0);
  });

  it('referrers always signed up before the people they referred', () => {
    expect(one(`SELECT count(*) AS n FROM users u JOIN users r ON r.user_id = u.referred_by WHERE r.signup_date >= u.signup_date`).n).toBe(0);
  });
});
